theme: jekyll-theme-minimal

title: trust|me
description: This is the trust|me project documentation
githuborg: https://github.com/trustm3
repository: trustme_main
release_tag: v0.1
markdown: kramdown
